test_format = 1.0

[default]
    args.pages_enable = false
    args.pages_url = ""

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4de0c3b.name = "Upgrade from 18.11.3"
