test_format = 1.0

[default]
    args.pages_enable = false
    args.pages_url = ""
    
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4de0c3b.name = "Upgrade from 18.11.3"

[pages]
    args.pages_enable = true
    args.pages_url = "domain.tld"

    only = ["install.root", "backup_restore", "upgrade"]

[enterprise]
    args.pages_enable = false
    args.pages_url = ""
    args.gitlab_edition = "Enterprise"

    only = ["install.root"]