#!/bin/bash

source /usr/share/yunohost/helpers

#REMOVEME? ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__use_web_account() {
    if [ -n "${use_web_account}" ]
    then
        echo "ApplicationSetting.last.update(password_authentication_enabled_for_web: $use_web_account, signup_enabled: $use_web_account)" | gitlab-rails console

        # Update the config of the app
        ynh_app_setting_set --key=use_web_account --value=$use_web_account
    fi
}

#=================================================
ynh_app_config_run $1