#!/bin/bash

set -u

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Load common variables and helpers
source ./_common.sh

# Remove gitlab
dpkg --remove  gitlab-ce

# Remove Config
remove_config_gitlab

# Remove dependencies
ynh_remove_app_dependencies

# Remove a directory securely
ynh_secure_remove "/etc/$app"
ynh_secure_remove "/opt/$app"
ynh_secure_remove "/var/opt/$app"

# Remove the log files
ynh_secure_remove "/var/log/$app"

# Remove nginx configuration file
ynh_remove_nginx_config
