#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Source YunoHost helpers
source /usr/share/yunohost/helpers

sudo apt-get update
sudo apt-get install -yy gitlab-ce
